In [2]:
import pandas as pd

In [3]:
prodict_metadata = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/METADATA_PANCANCER_PAPER_260416.xlsx")

In [3]:
new_metadata = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/METADATA_PANCANCER_PAPER_260416.xlsx")

In [7]:
#display(prodict_metadata[['Sample name', 'code_oncotree']].head())
display(new_metadata[['Sample name', 'code_oncotree', 'oncotree_code_enrollment', 'PROdict']].head())

          Sample name code_oncotree oncotree_code_enrollment        PROdict
0  H021-9ZENZBK-M3-Q1         AMPCA                    AMPCA  TCC low or NA
1  H021-7YTCA83-M1-Q1          APAD                     APAD          TRAIN
2   H021-7QUJ2X-M2-Q1          APAD                     APAD           TEST
3  K26K-VNZ1KD-M11-Q1          BRCA                     BRCA          TRAIN
4  K26K-A927U9-M22-Q1          BRCA                     BRCA          TRAIN

In [15]:
prodict_metadata['Sample name'] = prodict_metadata['Sample name'].str.strip()
new_metadata['Sample name'] = new_metadata['Sample name'].str.strip()

In [16]:
comparison_df = prodict_metadata[['Sample name', 'code_oncotree']].merge(new_metadata[['Sample name', 'oncotree_code', 'oncotree_code_enrollment']], how="outer", on='Sample name')

In [17]:
comparison_df.head()

          Sample name code_oncotree oncotree_code oncotree_code_enrollment
0  A26K-5SXQR3-T11-Q1          BRCA          BRCA                     BRCA
1  A26K-5SXQR3-T24-Q1          BRCA          BRCA                     BRCA
2  A26K-9TET1N-T11-Q1          BRCA          BRCA                     BRCA
3  A26K-ADUQXR-T11-Q1          BRCA          BRCA                     BRCA
4  A26K-HS3BDB-T14-Q1          BRCA          BRCA                     BRCA

In [18]:
comparison_df['code_oncotree'] == comparison_df['oncotree_code']

0       True
1       True
2       True
3       True
4       True
        ...
1993    True
1994    True
1995    True
1996    True
1997    True
Length: 1998, dtype: bool

In [20]:
comparison_df[~(comparison_df['code_oncotree'] == comparison_df['oncotree_code'])].to_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/oncotree_code_updates.xlsx", index=False)

In [24]:
max(prodict_metadata['Batch_No'])
min(prodict_metadata['Batch_No'])

1

In [25]:
new_metadata

,Sample name,Patient_Identifier,PID,Batch_No,TMT_Channel,Program,QC,QC_PP_(intensity_ratio_ref),Histology,Tissue_of_origin,...,ICDO3_topo_version,oncotree_code_onkostar,oncotree_code_enrollment,MTBslide_filename.1,MTBslide_all_filenames.1,MTBslide_patient_id.1,MTBslide_date.1,MTBslide_match_type,incidence_per_100K,incidence_reference
0,H021-9ZENZBK-M3-Q1,9ZENZBK,P2539,253,9,MASTER,passed,passed,Adenocarcinoma,AMPULLA_OF_VATER,...,rev2de,AMPULLA_OF_VATER,AMPCA,H021-9ZENZBK-M3-Q1_proteomics_241111.pptx,H021-9ZENZBK-M3-Q1_proteomics_241111.pptx,H021-9ZENZBK-M3-Q1,2024-11-11,exact,0.6,SEER
1,H021-7YTCA83-M1-Q1,7YTCA83,P3148,314,8,MASTER,passed,passed,Adenocarcinoma,BOWEL,...,rev2de,APAD,APAD,H021-7YTCA83-M1-Q1_proteomics_250602.pptx,H021-7YTCA83-M1-Q1_proteomics_250602.pptx,H021-7YTCA83-M1-Q1,2025-06-02,exact,1.1,SEER
2,H021-7QUJ2X-M2-Q1,7QUJ2X,P1864,186,4,MASTER,passed,passed,Adenocarcinoma,BOWEL,...,rev2de,APAD,APAD,H021-7QUJ2X-M2-Q1_proteomics_240331.pptx,H021-7QUJ2X-M2-Q1_proteomics_240331.pptx,H021-7QUJ2X-M2-Q1,2024-03-31,exact,1.1,SEER
3,K26K-VNZ1KD-M11-Q1,VNZ1KD,P1647,164,7,CATCH,passed,failed,Adenocarcinoma,BREAST,...,NaN,NaN,BRCA,NaN,NaN,NaN,NaT,NaN,131,SEER
4,K26K-A927U9-M22-Q1,A927U9,P1707,170,7,CATCH,passed,passed,Adenocarcinoma,BREAST,...,NaN,NaN,BRCA,NaN,NaN,NaN,NaT,NaN,131,SEER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,H021-XP4W4J8-M1-Q1,XP4W4J8,P3037,303,7,MASTER,passed,passed,Squamous cell carcinoma,BLADDER,...,rev2de,BLSC,BLSC,H021-XP4W4J8-M1-Q1_proteomics_results_250522.pptx,H021-XP4W4J8-M1-Q1_proteomics_results_250522.pptx,H021-XP4W4J8-M1-Q1,2025-05-22,exact,3-10 (male-female),2-5% of bladder cancer
1994,H021-QYVBXUN-M1-Q1,QYVBXUN,P3271,327,1,MASTER,passed,passed,Squamous cell carcinoma,VULVA,...,rev2de,VULVA,VSC,H021-QYVBXUN-M1-Q1_proteomics_250703.pptx,H021-QYVBXUN-M1-Q1_proteomics_250703.pptx,H021-QYVBXUN-M1-Q1,2025-07-03,exact,NaN,rare subtype of SCC
1995,H021-HGR7VDP-M4-E3,HGR7VDP,P3302,330,2,MASTER,passed,passed,Squamous cell carcinoma,OTHER,...,rev2de,SNSC,SCCNOS,H021-HGR7VDP-M4-E3_proteomics_250712.pptx,H021-HGR7VDP-M4-E3_proteomics_250712.pptx,H021-HGR7VDP-M4-E3,2025-07-12,exact,NaN,no exact numbers
1996,H021-LQCK3RB-T1-E2,LQCK3RB,P3345,334,5,MASTER,passed,passed,Squamous cell carcinoma,HEAD_NECK,...,rev2de,OCSC,OCSC,H021-LQCK3RB-T1-E2_proteomics_results_250722.pptx,H021-LQCK3RB-T1-E2_proteomics_results_250722.pptx,H021-LQCK3RB-T1-E2,2025-07-22,exact,NaN,"very rare, no exact number"
1997,H021-HXWUFC-M1-Q1,HXWUFC,P1851,185,1,MASTER,passed,passed,Adenocarcinoma,HEAD_NECK,...,rev2de,SNUC,SNUC,H021-HXWUFC-M1-Q1_proteomics_240319.pptx,H021-HXWUFC-M1-Q1_proteomics_240319.pptx,H021-HXWUFC-M1-Q1,2024-03-19,exact,0.02,SEER

In [26]:
prodict_metadata

,Unnamed: 0,Sample name,Batch_No,TMT_Channel,Program,Patient_Identifier,QC,QC_PP_(intensity_ratio_ref),MULTIPLE samples_passed,code_oncotree,...,PP sum ratio to ref,FP between_batch_correction_factor,PP between_batch_correction_factor,FP in_batch_correction_factor,PP in_batch_correction_factor,Paper_extv2,QC_old,Multiple samples_info,PID,PROdict
0,0,A26K-5SXQR3-T11-Q1,141,5,CATCH,5SXQR3,passed,passed,MULTIPLE,BRCA,...,0.389946,3.589,0.6741,0.9772,0.9965,no,passed,missing,P1415,NaN
1,1,A26K-5SXQR3-T24-Q1,141,6,CATCH,5SXQR3,passed,passed,MULTIPLE,BRCA,...,0.326845,3.589,0.6741,1.247,1.225,yes,passed,missing,P1416,NaN
2,2,A26K-9TET1N-T11-Q1,180,2,CATCH,9TET1N,passed,passed,EXTRACTION REPLICATE,BRCA,...,0.859303,0.7753,0.3517,0.9904,0.8775,yes,passed,missing,P1802,NaN
3,3,A26K-ADUQXR-T11-Q1,145,1,CATCH,ADUQXR,passed,failed,MULTIPLE,BRCA,...,0.181131,3.691,0.4976,1.705,1.914,yes,passed,missing,P1451,NaN
4,4,A26K-HS3BDB-T14-Q1,99,1,CATCH,HS3BDB4,passed,passed,NONE,BRCA,...,0.571615,2.563,1.041,0.9305,0.8685,yes,passed,missing,P0991,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,1993,S033-33+029-T1-Q1,141,2,MASTER,S033-33+029,passed,failed,NONE,CHDM,...,0.180888,3.589,0.6741,2.123,2.981,yes,passed,missing,P1412,NaN
1994,1994,S033-33+030-T1-Q1,142,7,MASTER,S033-33+030,passed,passed,NONE,CHDM,...,0.436816,2.546,0.4129,1.161,1.266,yes,passed,missing,P1427,NaN
1995,1995,S033-33+035-T1-Q1,157,7,MASTER,S033-33+035,passed,passed,NONE,CHDM,...,0.70917,0.7893,1.691,0.7949,0.7285,yes,passed,missing,P1577,NaN
1996,1996,S033-33+036-T1-Q1,157,8,MASTER,S033-33+036,passed,passed,NONE,CHDM,...,0.393267,0.7893,1.691,1.566,1.511,no,passed,missing,P1578,NaN
1997,1997,S033-33+038-T1-Q1,159,8,MASTER,S033-33+038,passed,failed,NONE,CHDM,...,0.193748,1.176,1.214,2.494,2.651,no,passed,missing,P1598,NaN

In [9]:
new_metadata['code_oncotree'].str.endswith("NOS").sum()

np.int64(204)

### PRODICT column redoing

In [50]:
new_metadata = pd.read_excel("/media/kusterlab/internal_projects/active/TOPAS/Publications/WP3_MTBpaper_CancerCell/Figure 2/METADATA_PANCANCER_PAPER_260416.xlsx")

In [52]:
new_metadata['PROdict']

0               TRAIN
1                TEST
2               TRAIN
3               TRAIN
4                TEST
            ...
1993    TCC low or NA
1994    TCC low or NA
1995              NOS
1996            TRAIN
1997             TEST
Name: PROdict, Length: 1998, dtype: object

In [ ]:
ho = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/held_out_df.xlsx", usecols='Sample name')

In [20]:
train = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/initial_training_df.xlsx", usecols='A')
nos = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/removed_samples_CUPNOS_NECNOS_NETNOS_SARCNOS_RCSNOS_SCCNOS_missing.xlsx", usecols='A')
low_tcc = pd.read_excel("/home/lestrada/projects/ProDICT/data/_cohort_files/removed_samples_very low_notdefined.xlsx", usecols='A')

In [42]:
new_metadata[new_metadata['Sample name'].isin(ho['Sample name'])]['PROdict'].value_counts()

PROdict
TEST    467
Name: count, dtype: int64

In [54]:
new_metadata['PROdict']

0         TRAIN
1          TEST
2         TRAIN
3         TRAIN
4         TRAIN
         ...
1993    low_tcc
1994    low_tcc
1995        NOS
1996      TRAIN
1997      TRAIN
Name: PROdict, Length: 1998, dtype: object

In [53]:
new_metadata['PROdict'] = pd.NA

new_metadata.loc[
    new_metadata['Sample name'].isin(train['Sample name']),
    'PROdict'
] = "TRAIN"

new_metadata.loc[
    new_metadata['Sample name'].isin(nos['Sample name']),
    'PROdict'
] = "NOS"

new_metadata.loc[
    new_metadata['Sample name'].isin(low_tcc['Sample name']),
    'PROdict'
] = "low_tcc"

new_metadata.loc[
    new_metadata['Sample name'].isin(ho['Sample name']),
    'PROdict'
] = "TEST"

In [59]:
set(train['Sample name']) & set(ho['Sample name']) #& set(low_tcc['Sample name']) & set(ho['Sample name'])

set()

In [60]:
new_metadata.to_excel("/media/kusterlab/internal_projects/active/TOPAS/Publications/WP3_MTBpaper_CancerCell/Figure 2/METADATA_PANCANCER_PAPER_260416.xlsx", index=False)